apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishchain-frontend
  namespace: fishchain
  labels:
    app: fishchain-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fishchain-frontend
  template:
    metadata:
      labels:
        app: fishchain-frontend
    spec:
      containers:
        - name: frontend
          image: fish-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 3
            periodSeconds: 20
            failureThreshold: 3
