apiVersion: v1
kind: Service
metadata:
  name: fishchain-frontend
  namespace: fishchain
spec:
  selector:
    app: fishchain-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
